# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'd:\Github\pyqt-vlc\pyqt\MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MediaPlayer(object):
    def setupUi(self, MediaPlayer):
        MediaPlayer.setObjectName("MediaPlayer")
        MediaPlayer.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MediaPlayer)
        self.centralwidget.setObjectName("centralwidget")
        MediaPlayer.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MediaPlayer)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        self.menuNetWork_Stream = QtWidgets.QMenu(self.menubar)
        self.menuNetWork_Stream.setObjectName("menuNetWork_Stream")
        MediaPlayer.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MediaPlayer)
        self.statusbar.setObjectName("statusbar")
        MediaPlayer.setStatusBar(self.statusbar)
        self.actionStream = QtWidgets.QAction(MediaPlayer)
        self.actionStream.setCheckable(False)
        self.actionStream.setObjectName("actionStream")
        self.menuNetWork_Stream.addAction(self.actionStream)
        self.menubar.addAction(self.menuNetWork_Stream.menuAction())

        self.retranslateUi(MediaPlayer)
        QtCore.QMetaObject.connectSlotsByName(MediaPlayer)

    def retranslateUi(self, MediaPlayer):
        _translate = QtCore.QCoreApplication.translate
        MediaPlayer.setWindowTitle(_translate("MediaPlayer", "MainWindow"))
        self.menuNetWork_Stream.setTitle(_translate("MediaPlayer", "Open"))
        self.actionStream.setText(_translate("MediaPlayer", "Stream"))
        self.actionStream.setShortcut(_translate("MediaPlayer", "Ctrl+O"))
